AWSTemplateFormatVersion: 2010-09-09

Description: |
  Capstone Project CloudFormation Servers Deployment.
  - Launch Configuration and Group
  - Application Load Balancer
  - Bastion Host
  - IAM Service Role
  - Security Group

Parameters:

  ENVIRONMENTNAME:
    Description: An environment name that will be prefixed to resource names.
    Type: String

  MYIP:
    Description: Home IP to access the bastion
    Type: String
    Default: 79.155.6.195/32
    
  EKSROLE:
    Description: Role Assigned to the EKS Cluster
    Type: String
    Default: arn:aws:iam::628641662978:role/eksServiceRole

  EKSNODEGROUPROLE:
    Description: Role Assigned to the EKS NodeGroup
    Type: String
    Default: arn:aws:iam::628641662978:role/NodeInstanceRole

Resources:

  EKSSECURITUGROUP:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: EKS Cluster Security Group
      Tags: 
        - Key: Environment
          Value: !Ref ENVIRONMENTNAME
        -
          Key: Name
          Value: !Sub ${ENVIRONMENTNAME}-WEBSERVERGROUP
      VpcId:
        Fn::ImportValue: capstone-stack-VPC

  EKSSECURITUGROUPINGRESS:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EKSSECURITUGROUP
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref EKSSECURITUGROUP

  EKSCLUSTER:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: EKSCLUSTER
      Version: '1.15'
      RoleArn: !Ref EKSROLE
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EKSSECURITUGROUP
        SubnetIds:
          - Fn::ImportValue: capstone-stack-PUBSUBNET1
          - Fn::ImportValue: capstone-stack-PUBSUBNET2

  EKSNODEGROUP:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Ref EKSCLUSTER
      NodeRole: !Ref EKSNODEGROUPROLE
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 3
      Subnets:
        - Fn::ImportValue: capstone-stack-PUBSUBNET1
        - Fn::ImportValue: capstone-stack-PUBSUBNET2